// ==========================================================================
// Board blueprint (generateBoardBlueprint, appendMissingBoardMembers): for the Minimal application
// (tests/fixtures/app, generated by tests/app_gen_test.js into <dir>) writes a board that the application must
// compile against (run.sh), and checks that a later export appends exactly what is missing, keeping the rest.
//   node tests/board_test.js <dir>
// ==========================================================================
'use strict';
const fs = require('fs'), path = require('path'), Module = require('module');
const load = Module._load;
Module._load = function (r, ...a) { return r === 'vscode' ? {} : load.call(this, r, ...a); };
const ext = require(path.join(__dirname, '..', 'out', 'extension.js'));
const dir = process.argv[2];
let failures = 0;
const check = (name, ok, detail) => { console.log(`${ok ? 'PASS' : 'FAIL'}  board: ${name}${ok ? '' : ' — ' + detail}`); if (!ok) failures++; };

const app = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'app', 'minimal.app.json'), 'utf8'));
app.board = { type: 'Board::Generated', header: 'generated_board.hpp' };
const owners = ['Timebomb', 'ButtonPoller', 'Tap', 'Adc', 'Samples', 'RxIrq', 'Rx', 'Log'];
const sources = owners.map(o => ({ owner: o, content: fs.readFileSync(path.join(dir, `${o.toLowerCase()}_hw_requirements.hpp`), 'utf8') }));
// ButtonPoller's generated requirements are empty: declare what it reads, as its designer would
sources.find(s => s.owner === 'ButtonPoller').content = 'namespace ButtonPoller { struct HwRequirements { static bool read_button(); }; }';

const board = ext.generateBoardBlueprint(app, sources);
// The same application on the generated board: only its app header and source differ, written to <dir>/on_board (run.sh compiles it)
const models = [ext.describeHsmModel('timebomb.hsm.json', fs.readFileSync(path.join(__dirname, 'fixtures', 'timebomb.hsm.json'), 'utf8'))];
fs.mkdirSync(path.join(dir, 'on_board'), { recursive: true });
fs.writeFileSync(path.join(dir, 'on_board', 'generated_board.hpp'), board);
const files = ext.generateAppFiles(app, models, owners);
for (const file of ['app.hpp', 'app.cpp']) fs.writeFileSync(path.join(dir, 'on_board', file), files[file]);   // the rest is the same
check('the blueprint has the modules\' functions, interrupts and the features\' functions, each once',
      ['set_led(bool on)', 'read_button()', 'tap_ack()', 'uint16_t adc_ack()', 'size_t rx_ack()', 'trace_write(', 'watchdog_kick()', 'reset_cause()']
          .every(s => board.includes(s)) && board.split('read_button(').length === 2 &&
      /struct Irq \{[\s\S]*static constexpr int tap = 0;[\s\S]*static constexpr int adc = 1;[\s\S]*static constexpr int rx = 2;/.test(board) &&
      board.includes('namespace Board {') && board.includes('struct Generated {'), board);
check('a function two modules require is listed once, naming both', /required by Timebomb, ButtonPoller\n\s*static bool read_button\(\)/.test(board), board);
check('nothing to append to a complete board', ext.appendMissingBoardMembers(board, app, sources).added.length === 0,
      JSON.stringify(ext.appendMissingBoardMembers(board, app, sources).added));

// A board written by hand from the blueprint, then the application grows: a new driver function and interrupt
const handWritten = board.replace('static bool read_button() { return {}; /* TODO */ }', 'static bool read_button() { return (GPIOC_IDR & 0x2000) != 0; }   // mine')
                         .replace(/\s*static constexpr int rx = 2;[^\n]*/, '');
const grown = sources.concat([{ owner: 'Display', content: 'namespace Display { struct HwRequirements { static void show(uint8_t digit); // 7-segment\n struct Irq { static const int vsync; }; }; }' }]);
const { updated, added } = ext.appendMissingBoardMembers(handWritten, app, grown);
check('a later export adds what is missing (a function into its section, interrupts into Irq), marked, and keeps the hand-written code',
      JSON.stringify(added.sort()) === JSON.stringify(['Irq::rx', 'Irq::vsync', 'show'].sort()) &&
      updated.includes('return (GPIOC_IDR & 0x2000) != 0; }   // mine') &&
      // in the DRIVERS section (the blueprint's banner is still there), before TRACE, its comment in the TODO
      /\/\/ DRIVERS[\s\S]*static void show\(uint8_t digit\) \{ \(void\)digit; \/\* TODO \*\/ \}   \/\/ TODO \(added by export\): 7-segment\n\n[\s\S]*\/\/ TRACE/.test(updated) &&
      !updated.includes('Added by export') &&
      /struct Irq \{[^}]*static constexpr int vsync = 20\d;   \/\/ TODO \(added by export\)/.test(updated), updated);
const plain = 'namespace Board {\nstruct Generated {\n    static void init() {}\n};\n}\n';
const fromPlain = ext.appendMissingBoardMembers(plain, app, sources).updated;
check('a board without the blueprint\'s sections gets the missing members in one marked block at its end',
      /static void init\(\) \{\}\n\n    \/\/ ---- Added by export[^\n]*\n[\s\S]*static bool read_button\(\)[\s\S]*\n\};\n\}/.test(fromPlain), fromPlain);
check('appending again changes nothing', ext.appendMissingBoardMembers(updated, app, grown).updated === updated, '');
process.exit(failures ? 1 : 0);
